name: Deployement

on:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest 
    container:
      image: 'djelale/assistme:1.0.0' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and build client
        run: |
          cd client
          npm install
          npm run build

      - name: Install and build server
        run: |
          cd server
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Deploy to Render
        run: |
          echo "Deploying to Render..."
          curl -X POST "https://api.render.com/v1/services/${{ cs97c968ii6s73ev820g }}/deploys" \
          -H "Authorization: Bearer ${{ rnd_jVLom5W5VJCXweycehqwPCUBoDnk }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}'