name: Deployment

on:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest 
    container:
      image: 'djelale/assistme:1.0.0' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and build client
        run: |
          cd client
          npm install
          npm run build

      - name: Install and build server
        run: |
          cd server
          npm install
          npm run build


  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy frontend to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.FRONTEND_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}'

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy backend to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.BACKEND_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}'